sudo: required

language: php
php:
  - "7.1"
  - "7.0"
  - "5.6"

env:
  - APPLICATION_ENV=test

services:
  - docker

install:
  - composer install
  - composer restdocs
  - composer migrate -- reset --yes
  - composer build
  - docker ps -a
  - sleep 15
  - docker ps -a
  - "curl -X GET \"http://127.0.0.1/sample/ping\" -H  \"accept: application/json\""
  - docker inspect resttemplate-test-instance
  - docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' resttemplate-test-instance
  - sudo chown 82:82 src/sample.db
  - sudo chown 82:82 src/
  - "curl -X GET \"http://127.0.0.1/sample/ping\" -H  \"accept: application/json\""

script:
  - phpunit
